alias c='clear'
alias q='exit'
alias pn='pnpm'
alias cat='bat'
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias gl='git log --oneline --graph --decorate --all'
alias dt='docker run -it --rm -v $(pwd):/tmp fedora:latest /bin/bash'
